### ISSUE TITLE
Move to different snap name

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_smart-device#144]
The snap of cbj_smart_device use the snap name cybear-jinni, it need  to move to cbj-smart-device.
cybear-jinni will be used by the app, on all platform the app should have only the company name.

![image](https://user-images.githubusercontent.com/9304740/126297435-545bd742-609f-4a07-a6be-126c553265d9.png)

**Comment by guyluz11** [comment]
Moved out of the snap, will need to move in to the new one.
For now this program does not have snapstore install.

**Comment by guyluz11** [comment]
This is the new URL of the snap

Please fix it in the Readme file

https://snapcraft.io/cbj-smart-device

**Comment by ranaashutosh2923** [comment]
Hello Sir, Can you assign this issue to me?

**Comment by guyluz11** [comment]
Done
