### ISSUE TITLE
Readme dart ci bage is icorrect

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_smart-device#153]
Readme dart ci bage is incorrect

It is currently 

`[dart CI](https://github.com/CyBear-Jinni/CBJ_Smart-Device/workflows/Dart%20CI/badge.svg)](https://github.com/CyBear-Jinni/CBJ_Smart-Device/actions?query=workflow%3A%22Dart+CI%22)`

But the repo name has changed from `CBJ_Smart-Device` to `cbj_smart-device`

**Comment by BxtGeek** [comment]
I want contribute on this

**Comment by guyluz11** [comment]
Ok, yours @BxtGeek

**Comment by BxtGeek** [comment]
Changes are added

**Comment by guyluz11** [comment]
But there is no open pr

**Comment by BxtGeek** [comment]
I raise a PR now

**Comment by guyluz11** [comment]
Hi @BxtGeek I am removing you from Assignees but your pr will still be merged if it comes first.

Thanks

**Comment by guyluz11** [comment]
Pr merged

Thanks
