### ISSUE TITLE
Adding badges to readme

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_Smart-Device#37]
Please make the text "CyBear Jinni Smart Device" center and below it add the image 

<p align="center">
<img src="https://user-images.githubusercontent.com/9304740/94843279-24a49900-0425-11eb-83f3-87e8ba40b1dc.png" height="300" alt="CyBear Jinni" />
</p>

to the readme and center it.

Below that add the following badges:

Dart CI (passing), effective dart, license (GPL 3.0), Open Source heart.

[![Github Action Status](https://github.com/CyBear-Jinni/CBJ_Smart-Device/workflows/Dart%20CI/badge.svg)](https://github.com/CyBear-Jinni/CBJ_Smart-Device/actions)

[![style: effective dart](https://img.shields.io/badge/style-effective_dart-40c4ff.svg)](https://pub.dev/packages/effective_dart)

[![License: GPL-3.0](https://img.shields.io/badge/license-GPL3.0-blue.svg)](https://github.com/CyBear-Jinni/CBJ_Smart-Device/blob/master/LICENSE)

 
![image](https://user-images.githubusercontent.com/9304740/94861713-a229d280-0440-11eb-9c54-344e5d92520a.png)

Below the badges the readme text should start

**Comment by felipedotcom** [comment]
can i take this one?

**Comment by guyluz11** [comment]
Sure @felipedotcom

**Comment by felipedotcom** [comment]
done!

**Comment by guyluz11** [comment]
#40  

I have add comments. 
Thanks

**Comment by felipedotcom** [comment]
fixed

**Comment by guyluz11** [comment]
#42 

Thanks @felipedotcom
