### ISSUE TITLE
Readme file small fixes

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_Smart-Device#47]
Please make the CyBear Jinni image in the readme smaller 

Use this lines of code  

[<div align="center"><img alt="CyBear Jinni image" height="300" src="https://user-images.githubusercontent.com/9304740/94843279-24a49900-0425-11eb-83f3-87e8ba40b1dc.png">](https://github.com/CyBear-Jinni/CBJ_Smart-Home)
</div>

```html
[<div align="center"><img alt="CyBear Jinni image" height="300" src="https://user-images.githubusercontent.com/9304740/94843279-24a49900-0425-11eb-83f3-87e8ba40b1dc.png">](https://github.com/CyBear-Jinni/CBJ_Smart-Home)
</div>
```

And move the badges to be above it.

**Comment by krish7777** [comment]
@guyluz11 Can I work on this?

**Comment by guyluz11** [comment]
Sure @krish7777

**Comment by guyluz11** [comment]
Thanks @krish7777
