### ISSUE TITLE
Move parts in readme

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_Smart-Device#51]
Please move the `disclaimers` part below `Social Media Links` part

https://github.com/CyBear-Jinni/CBJ_Smart-Device/tree/dev#disclaimers

**Comment by uzair-ashraf** [comment]
Completed! https://github.com/CyBear-Jinni/CBJ_Smart-Device/pull/53

**Comment by guyluz11** [comment]
@uzair-ashraf 

I Commented on the issue, please open it again to dev.

**Comment by lix-dev** [comment]
completed #60

**Comment by guyluz11** [comment]
I am sorry @uzair-ashraf but as I saw that you are not active I have moved the issue to @lix-dev 

Thanks everyone.
