### ISSUE TITLE
Markdown License badges change in readme

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_Smart-Device#65]
Found out that we put the wrong badge for the license in the readme.
Please update the license badge to the new one.

[![License: AGPL v3](https://img.shields.io/badge/License-AGPL%20v3-blue.svg)](https://www.gnu.org/licenses/agpl-3.0)

`[![License: AGPL v3](https://img.shields.io/badge/License-AGPL%20v3-blue.svg)](https://www.gnu.org/licenses/agpl-3.0)`

**Comment by Devanshh** [comment]
Hi @guyluz11 , Can I take this up?

**Comment by uabua** [comment]
Hello. I already changed License badge in README.md da made PR. Please, assign this issue to me and close it. Thank you! ⭐

**Comment by guyluz11** [comment]
I am sorry @Devanshh  but the issue is already have been fixed

**Comment by Devanshh** [comment]
But I asked for the assignment before. And already created the PR well before @uabua
