### ISSUE TITLE
Bash script need small fix for edge case

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_Smart-Device#66]
It seems that the Linux Bash command `uname -p` does not wok on all the OS's and return `unknown` and not the architecture of the device CPU.

I found out the using the command `uname -m` solve it.

So for this page [dartSdkDownload.sh](https://github.com/CyBear-Jinni/CBJ_Smart-Device/blob/master/scripts/bashScripts/dartSdkDownload.sh) please change `uname -p` to `uname -m`.

**Comment by Tazminia** [comment]
Hello, I can do the requested change

**Comment by guyluz11** [comment]
Sure @Tazminia

**Comment by guyluz11** [comment]
@Tazminia Thanks for the pr, now closing this issue.
