### ISSUE TITLE
Change the Open Source badge

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_Smart-Device#75]
The `Open Source` badge is low quality.

Please update it to be the same as the one in our  [CBJ_App](https://github.com/CyBear-Jinni/CBJ_App) readme as it have better quality.

**Comment by 0xln** [comment]
Commenting on the issue, so it can be assigned to me

**Comment by guyluz11** [comment]
Thanks @0xln for the pull request
