### ISSUE TITLE
Add linux badge to the project readme

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_Smart-Device#79]
Please add a badge of Linux to the project.

Example can be found in the readme of this repository:
https://github.com/aristocratos/bpytop

Please link it to the Linux [wikipedi](https://en.wikipedia.org/wiki/Linux) 

![image](https://user-images.githubusercontent.com/9304740/95691001-55a27c00-0c24-11eb-8b48-d6b426424d0d.png)

**Comment by georgioupanayiotis** [comment]
can you assign me ?

**Comment by guyluz11** [comment]
Sure

**Comment by georgioupanayiotis** [comment]
Created the change here https://github.com/CyBear-Jinni/CBJ_Smart-Device/pull/80/commits/170fa7ababb799aee3f21231bc392f14d0676b39

**Comment by guyluz11** [comment]
Hi @georgioupanayiotis 

Can you reopen the pull request to `dev` branch?

Thanks

**Comment by guyluz11** [comment]
I have decided that this badge is redundant, will now close the issue
