### ISSUE TITLE
Add snap badge to readme file

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_Smart-Device#81]
Add snap badge to readme file example can be found here

https://github.com/tqdm/tqdm

![image](https://user-images.githubusercontent.com/9304740/95691445-f7779800-0c27-11eb-8cd6-066945853712.png)

Make it link to [our page](https://snapcraft.io/cybear-jinni) in the snapcraft store 

I prefer the new logo with the orange nose if you can fined as a badge or create it. 

![image](https://user-images.githubusercontent.com/9304740/95694250-aa9cbd00-0c39-11eb-862d-65e6b801e2dd.png)

**Comment by sofiacarballo** [comment]
Hi! I'd like to work on this :)

**Comment by guyluz11** [comment]
Sure @sofiacarballo 


1. Please insert the badge to the left side before the `Dart CI`
2. Open the pull request to `dev` branch

**Comment by sofiacarballo** [comment]
> Sure @sofiacarballo
> 
> 1. Please insert the badge to the left side before the `Dart CI`
> 2. Open the pull request to `dev` branch

I've just sent the PR, if you would like that I modify something just let me know.

**Comment by sofiacarballo** [comment]
@guyluz11 I've just made the PR. If there's something that needs to be modified just let me know 😄

**Comment by guyluz11** [comment]
Thanks @sofiacarballo for adding the new badge with the new logo of snapcraft.

The pull request got merged so I will now close this issue.
